<?php

/**
 * This is the model base class for the table "pe_anggaran_detil".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PeAnggaranDetil".
 *
 * Columns in table "pe_anggaran_detil" available as properties of the model,
 * followed by relations of table "pe_anggaran_detil" available as properties of the model.
 *
 * @property integer $id
 * @property integer $anggaran_id
 * @property double $amount
 * @property string $account_code
 *
 * @property PeChartMaster $accountCode
 * @property PeAnggaran $anggaran
 */
abstract class BasePeAnggaranDetil extends GxActiveRecord
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'pe_anggaran_detil';
    }

    public static function representingColumn()
    {
        return 'account_code';
    }

    public function rules()
    {
        return array(
            array('anggaran_id, account_code', 'required'),
            array('anggaran_id', 'numerical', 'integerOnly' => true),
            array('amount', 'numerical'),
            array('account_code', 'length', 'max' => 15),
            array('amount', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, anggaran_id, amount, account_code', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'accountCode' => array(self::BELONGS_TO, 'PeChartMaster', 'account_code'),
            'anggaran' => array(self::BELONGS_TO, 'PeAnggaran', 'anggaran_id'),
        );
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'anggaran_id' => Yii::t('app', 'Anggaran'),
            'amount' => Yii::t('app', 'Amount'),
            'account_code' => Yii::t('app', 'Account Code'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;
        $criteria->compare('id', $this->id);
        $criteria->compare('anggaran_id', $this->anggaran_id);
        $criteria->compare('amount', $this->amount);
        $criteria->compare('account_code', $this->account_code);
        return new CActiveDataProvider(get_class($this), array(
            'criteria' => $criteria,
        ));
    }
}