<?php

/**
 * This is the model base class for the table "pe_donatur".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PeDonatur".
 *
 * Columns in table "pe_donatur" available as properties of the model,
 * followed by relations of table "pe_donatur" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $phone
 * @property string $alamat
 * @property integer $inactive
 * @property string $account_code
 *
 * @property PeChartMaster $accountCode
 * @property PeKasMasuk[] $peKasMasuks
 */
abstract class BasePeDonatur extends GxActiveRecord
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'pe_donatur';
    }

    public static function representingColumn()
    {
        return 'name';
    }

    public function rules()
    {
        return array(
            array('account_code', 'required'),
            array('inactive', 'numerical', 'integerOnly' => true),
            array('name', 'length', 'max' => 50),
            array('phone', 'length', 'max' => 30),
            array('account_code', 'length', 'max' => 15),
            array('alamat', 'safe'),
            array('name, phone, alamat, inactive', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, name, phone, alamat, inactive, account_code', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array(
            'accountCode' => array(self::BELONGS_TO, 'PeChartMaster', 'account_code'),
            'peKasMasuks' => array(self::HAS_MANY, 'PeKasMasuk', 'pe_donatur_id'),
        );
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'phone' => Yii::t('app', 'Phone'),
            'alamat' => Yii::t('app', 'Alamat'),
            'inactive' => Yii::t('app', 'Inactive'),
            'account_code' => Yii::t('app', 'Account Code'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;
        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('phone', $this->phone, true);
        $criteria->compare('alamat', $this->alamat, true);
        $criteria->compare('inactive', $this->inactive);
        $criteria->compare('account_code', $this->account_code);
        return new CActiveDataProvider(get_class($this), array(
            'criteria' => $criteria,
        ));
    }
}