<?php

/**
 * This is the model base class for the table "pah_bank_trans".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PahBankTrans".
 *
 * Columns in table "pah_bank_trans" available as properties of the model,
 * followed by relations of table "pah_bank_trans" available as properties of the model.
 *
 * @property integer $id
 * @property integer $type
 * @property integer $trans_no
 * @property integer $bank_act
 * @property string $ref
 * @property string $trans_date
 * @property double $amount
 * @property integer $person_type_id
 * @property string $person_id
 * @property string $reconciled
 *
 * @property PahBankAccounts $bankAct
 */
abstract class BasePahBankTrans extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pah_bank_trans';
	}

	public static function representingColumn() {
		return 'ref';
	}

	public function rules() {
		return array(
			array('type, trans_no, bank_act, person_type_id', 'numerical', 'integerOnly'=>true),
			array('amount', 'numerical'),
			array('ref', 'length', 'max'=>40),
			array('trans_date, person_id, reconciled', 'safe'),
			array('type, trans_no, bank_act, ref, trans_date, amount, person_type_id, person_id, reconciled', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, type, trans_no, bank_act, ref, trans_date, amount, person_type_id, person_id, reconciled', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bankAct' => array(self::BELONGS_TO, 'PahBankAccounts', 'bank_act'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'type' => Yii::t('app', 'Type'),
			'trans_no' => Yii::t('app', 'Trans No'),
			'bank_act' => Yii::t('app', 'Bank Act'),
			'ref' => Yii::t('app', 'Ref'),
			'trans_date' => Yii::t('app', 'Trans Date'),
			'amount' => Yii::t('app', 'Amount'),
			'person_type_id' => Yii::t('app', 'Person Type'),
			'person_id' => Yii::t('app', 'Person'),
			'reconciled' => Yii::t('app', 'Reconciled'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('type', $this->type);
		$criteria->compare('trans_no', $this->trans_no);
		$criteria->compare('bank_act', $this->bank_act);
		$criteria->compare('ref', $this->ref, true);
		$criteria->compare('trans_date', $this->trans_date, true);
		$criteria->compare('amount', $this->amount);
		$criteria->compare('person_type_id', $this->person_type_id);
		$criteria->compare('person_id', $this->person_id, true);
		$criteria->compare('reconciled', $this->reconciled, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}