<?php

/**
 * This is the model base class for the table "pah_donatur".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PahDonatur".
 *
 * Columns in table "pah_donatur" available as properties of the model,
 * followed by relations of table "pah_donatur" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $phone
 * @property string $alamat
 * @property integer $inactive
 * @property string $pah_chart_master_account_code
 *
 * @property PahChartMaster $pahChartMasterAccountCode
 * @property PahKasMasuk[] $pahKasMasuks
 */
abstract class BasePahDonatur extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'pah_donatur';
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('pah_chart_master_account_code', 'required'),
			array('inactive', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>50),
			array('phone', 'length', 'max'=>30),
			array('pah_chart_master_account_code', 'length', 'max'=>15),
			array('alamat', 'safe'),
			array('name, phone, alamat, inactive', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, phone, alamat, inactive, pah_chart_master_account_code', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'pahChartMasterAccountCode' => array(self::BELONGS_TO, 'PahChartMaster', 'pah_chart_master_account_code'),
			'pahKasMasuks' => array(self::HAS_MANY, 'PahKasMasuk', 'pah_donatur_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'phone' => Yii::t('app', 'Phone'),
			'alamat' => Yii::t('app', 'Alamat'),
			'inactive' => Yii::t('app', 'Inactive'),
			'pah_chart_master_account_code' => Yii::t('app', 'Pah Chart Master Account Code'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('alamat', $this->alamat, true);
		$criteria->compare('inactive', $this->inactive);
		$criteria->compare('pah_chart_master_account_code', $this->pah_chart_master_account_code);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}