<?php
/**********************************************************************
    Copyright (C) FrontAccounting, LLC.
	Released under the terms of the GNU General Public License, GPL, 
	as published by the Free Software Foundation, either version 3 
	of the License, or (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
    See the License here <http://www.gnu.org/licenses/gpl-3.0.html>.
***********************************************************************/
require_once(Yii::app()->basePath. '/vendors/frontaccounting/types.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/sysnames.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/ui/ui_lists.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/ui/ui_controls.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/ui/ui_input.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/ui/ui_view.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/date_functions.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/current_user.inc');

//include_once($path_to_root . "/includes/ui/ui_lists.inc");
//include_once($path_to_root . "/includes/ui/ui_controls.inc");
//include_once($path_to_root . "/includes/ui/ui_input.inc");
//include_once($path_to_root . "/includes/ui/ui_msgs.inc");
//include_once($path_to_root . "/includes/ui/ui_globals.inc");
//include_once($path_to_root . "/includes/ui/ui_view.inc");
//include_once($path_to_root . "/includes/data_checks.inc");

?>