<?php

/**
 * This is the model base class for the table "users".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Users".
 *
 * Columns in table "users" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $user_id
 * @property string $password
 * @property string $real_name
 * @property integer $role_id
 * @property string $phone
 * @property string $email
 * @property string $language
 * @property integer $date_format
 * @property integer $date_sep
 * @property integer $tho_sep
 * @property integer $dec_sep
 * @property string $theme
 * @property string $page_size
 * @property integer $prices_dec
 * @property integer $qty_dec
 * @property integer $rates_dec
 * @property integer $percent_dec
 * @property integer $show_gl
 * @property integer $show_codes
 * @property integer $show_hints
 * @property string $last_visit_date
 * @property integer $query_size
 * @property integer $graphic_links
 * @property integer $pos
 * @property string $print_profile
 * @property integer $rep_popup
 * @property integer $sticky_doc_date
 * @property string $startup_tab
 * @property integer $inactive
 *
 */
abstract class BaseUsers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'users';
	}

	public static function representingColumn() {
		return 'user_id';
	}

	public function rules() {
		return array(
			array('role_id, date_format, date_sep, tho_sep, dec_sep, prices_dec, qty_dec, rates_dec, percent_dec, show_gl, show_codes, show_hints, query_size, graphic_links, pos, rep_popup, sticky_doc_date, inactive', 'numerical', 'integerOnly'=>true),
			array('user_id', 'length', 'max'=>60),
			array('password, real_name, email', 'length', 'max'=>100),
			array('phone, print_profile', 'length', 'max'=>30),
			array('language, theme, page_size, startup_tab', 'length', 'max'=>20),
			array('last_visit_date', 'safe'),
			array('user_id, password, real_name, role_id, phone, email, language, date_format, date_sep, tho_sep, dec_sep, theme, page_size, prices_dec, qty_dec, rates_dec, percent_dec, show_gl, show_codes, show_hints, last_visit_date, query_size, graphic_links, pos, print_profile, rep_popup, sticky_doc_date, startup_tab, inactive', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, password, real_name, role_id, phone, email, language, date_format, date_sep, tho_sep, dec_sep, theme, page_size, prices_dec, qty_dec, rates_dec, percent_dec, show_gl, show_codes, show_hints, last_visit_date, query_size, graphic_links, pos, print_profile, rep_popup, sticky_doc_date, startup_tab, inactive', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => Yii::t('app', 'User'),
			'password' => Yii::t('app', 'Password'),
			'real_name' => Yii::t('app', 'Real Name'),
			'role_id' => Yii::t('app', 'Role'),
			'phone' => Yii::t('app', 'Phone'),
			'email' => Yii::t('app', 'Email'),
			'language' => Yii::t('app', 'Language'),
			'date_format' => Yii::t('app', 'Date Format'),
			'date_sep' => Yii::t('app', 'Date Sep'),
			'tho_sep' => Yii::t('app', 'Tho Sep'),
			'dec_sep' => Yii::t('app', 'Dec Sep'),
			'theme' => Yii::t('app', 'Theme'),
			'page_size' => Yii::t('app', 'Page Size'),
			'prices_dec' => Yii::t('app', 'Prices Dec'),
			'qty_dec' => Yii::t('app', 'Qty Dec'),
			'rates_dec' => Yii::t('app', 'Rates Dec'),
			'percent_dec' => Yii::t('app', 'Percent Dec'),
			'show_gl' => Yii::t('app', 'Show Gl'),
			'show_codes' => Yii::t('app', 'Show Codes'),
			'show_hints' => Yii::t('app', 'Show Hints'),
			'last_visit_date' => Yii::t('app', 'Last Visit Date'),
			'query_size' => Yii::t('app', 'Query Size'),
			'graphic_links' => Yii::t('app', 'Graphic Links'),
			'pos' => Yii::t('app', 'Pos'),
			'print_profile' => Yii::t('app', 'Print Profile'),
			'rep_popup' => Yii::t('app', 'Rep Popup'),
			'sticky_doc_date' => Yii::t('app', 'Sticky Doc Date'),
			'startup_tab' => Yii::t('app', 'Startup Tab'),
			'inactive' => Yii::t('app', 'Inactive'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('real_name', $this->real_name, true);
		$criteria->compare('role_id', $this->role_id);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('language', $this->language, true);
		$criteria->compare('date_format', $this->date_format);
		$criteria->compare('date_sep', $this->date_sep);
		$criteria->compare('tho_sep', $this->tho_sep);
		$criteria->compare('dec_sep', $this->dec_sep);
		$criteria->compare('theme', $this->theme, true);
		$criteria->compare('page_size', $this->page_size, true);
		$criteria->compare('prices_dec', $this->prices_dec);
		$criteria->compare('qty_dec', $this->qty_dec);
		$criteria->compare('rates_dec', $this->rates_dec);
		$criteria->compare('percent_dec', $this->percent_dec);
		$criteria->compare('show_gl', $this->show_gl);
		$criteria->compare('show_codes', $this->show_codes);
		$criteria->compare('show_hints', $this->show_hints);
		$criteria->compare('last_visit_date', $this->last_visit_date, true);
		$criteria->compare('query_size', $this->query_size);
		$criteria->compare('graphic_links', $this->graphic_links);
		$criteria->compare('pos', $this->pos);
		$criteria->compare('print_profile', $this->print_profile, true);
		$criteria->compare('rep_popup', $this->rep_popup);
		$criteria->compare('sticky_doc_date', $this->sticky_doc_date);
		$criteria->compare('startup_tab', $this->startup_tab, true);
		$criteria->compare('inactive', $this->inactive);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}