<?php

require_once(Yii::app()->basePath. '/vendors/frontaccounting/types.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/sysnames.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/ui/ui_lists.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/ui/ui_controls.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/ui/ui_input.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/ui/ui_view.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/date_functions.inc');
require_once(Yii::app()->basePath. '/vendors/frontaccounting/current_user.inc');

?>