<?php

/**
 * This is the model base class for the table "pah_refs".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PahRefs".
 *
 * Columns in table "pah_refs" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $type_no
 * @property integer $type
 * @property string $reference
 *
 */
abstract class BasePahRefs extends GxActiveRecord
{
    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public function tableName()
    {
        return 'pah_refs';
    }

    public static function representingColumn()
    {
        return 'reference';
    }

    public function rules()
    {
        return array(
            array('type_no, type', 'numerical', 'integerOnly' => true),
            array('reference', 'length', 'max' => 100),
            array('type_no, type, reference', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, type_no, type, reference', 'safe', 'on' => 'search'),
        );
    }

    public function relations()
    {
        return array();
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('app', 'ID'),
            'type_no' => Yii::t('app', 'Type No'),
            'type' => Yii::t('app', 'Type'),
            'reference' => Yii::t('app', 'Reference'),
        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;
        $criteria->compare('id', $this->id);
        $criteria->compare('type_no', $this->type_no);
        $criteria->compare('type', $this->type);
        $criteria->compare('reference', $this->reference, true);
        return new CActiveDataProvider(get_class($this), array(
            'criteria' => $criteria,
        ));
    }
}