<?php

/**
 * This is the model base class for the table "sales".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Sales".
 *
 * Columns in table "sales" available as properties of the model,
 * followed by relations of table "sales" available as properties of the model.
 *
 * @property integer $sales_id
 * @property string $ref
 * @property string $name
 * @property string $address
 * @property string $phone
 * @property string $phone2
 * @property integer $inactive
 *
 * @property Nota[] $notas
 */
abstract class BaseSales extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sales';
	}

	public static function representingColumn() {
		return 'ref';
	}

	public function rules() {
		return array(
			array('inactive', 'numerical', 'integerOnly'=>true),
			array('ref, name, address, phone, phone2', 'safe'),
			array('ref, name, address, phone, phone2, inactive', 'default', 'setOnEmpty' => true, 'value' => null),
			array('sales_id, ref, name, address, phone, phone2, inactive', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'notas' => array(self::HAS_MANY, 'Nota', 'sales_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'sales_id' => Yii::t('app', 'Sales'),
			'ref' => Yii::t('app', 'Ref'),
			'name' => Yii::t('app', 'Name'),
			'address' => Yii::t('app', 'Address'),
			'phone' => Yii::t('app', 'Phone'),
			'phone2' => Yii::t('app', 'Phone2'),
			'inactive' => Yii::t('app', 'Inactive'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('sales_id', $this->sales_id);
		$criteria->compare('ref', $this->ref, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('phone', $this->phone, true);
		$criteria->compare('phone2', $this->phone2, true);
		$criteria->compare('inactive', $this->inactive);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}