<?php

/**
 * This is the model base class for the table "mt_pinjam_kendaraan".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MtPinjamKendaraan".
 *
 * Columns in table "mt_pinjam_kendaraan" available as properties of the model,
 * followed by relations of table "mt_pinjam_kendaraan" available as properties of the model.
 *
 * @property integer $id_pinjam
 * @property string $doc_ref
 * @property string $entry_time
 * @property string $trans_date
 * @property string $tanda_pengenal
 * @property string $no_identitas
 * @property string $jaminan
 * @property string $jaminan_desc
 * @property integer $id_pelanggan
 * @property integer $id_kelompok
 * @property string $tgl_pinjam
 * @property integer $season
 * @property integer $sewa_bln
 * @property integer $sewa_hari
 * @property integer $sewa_jam
 * @property string $trans_via
 * @property string $no_bukti_bayar
 * @property integer $id_driver
 * @property integer $id_mobil
 * @property double $ongkos_sewa
 * @property double $ongkos_driver
 * @property double $ongkos_bbm
 * @property double $total_ongkos
 * @property double $dp
 * @property double $sisa_tagihan
 * @property double $disc
 * @property double $total
 * @property string $tgl_rencana_kembali
 * @property integer $users_id
 * @property integer $is_back
 * @property double $trf_bulan
 * @property double $trf_hari
 * @property double $trf_jam
 *
 * @property MtKembaliKendaraan[] $mtKembaliKendaraans
 * @property MtPelanggan $idPelanggan
 * @property MtKelompokPelanggan $idKelompok
 * @property MtDriver $idDriver
 * @property MtMobil $idMobil
 * @property Users $users
 */
abstract class BaseMtPinjamKendaraan extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mt_pinjam_kendaraan';
	}

	public static function representingColumn() {
		return 'doc_ref';
	}

	public function rules() {
		return array(
			array('doc_ref, id_pelanggan, id_kelompok, id_mobil', 'required'),
			array('id_pelanggan, id_kelompok, season, sewa_bln, sewa_hari, sewa_jam, id_driver, id_mobil, users_id, is_back', 'numerical', 'integerOnly'=>true),
			array('ongkos_sewa, ongkos_driver, ongkos_bbm, total_ongkos, dp, sisa_tagihan, disc, total, trf_bulan, trf_hari, trf_jam', 'numerical'),
			array('doc_ref', 'length', 'max'=>15),
			array('tanda_pengenal, no_identitas, jaminan, trans_via', 'length', 'max'=>30),
			array('jaminan_desc', 'length', 'max'=>225),
			array('no_bukti_bayar', 'length', 'max'=>50),
			array('entry_time, trans_date, tgl_pinjam, tgl_rencana_kembali', 'safe'),
			array('entry_time, trans_date, tanda_pengenal, no_identitas, jaminan, jaminan_desc, tgl_pinjam, season, sewa_bln, sewa_hari, sewa_jam, trans_via, no_bukti_bayar, id_driver, ongkos_sewa, ongkos_driver, ongkos_bbm, total_ongkos, dp, sisa_tagihan, disc, total, tgl_rencana_kembali, users_id, is_back, trf_bulan, trf_hari, trf_jam', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_pinjam, doc_ref, entry_time, trans_date, tanda_pengenal, no_identitas, jaminan, jaminan_desc, id_pelanggan, id_kelompok, tgl_pinjam, season, sewa_bln, sewa_hari, sewa_jam, trans_via, no_bukti_bayar, id_driver, id_mobil, ongkos_sewa, ongkos_driver, ongkos_bbm, total_ongkos, dp, sisa_tagihan, disc, total, tgl_rencana_kembali, users_id, is_back, trf_bulan, trf_hari, trf_jam', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mtKembaliKendaraans' => array(self::HAS_MANY, 'MtKembaliKendaraan', 'id_pinjam'),
			'idPelanggan' => array(self::BELONGS_TO, 'MtPelanggan', 'id_pelanggan'),
			'idKelompok' => array(self::BELONGS_TO, 'MtKelompokPelanggan', 'id_kelompok'),
			'idDriver' => array(self::BELONGS_TO, 'MtDriver', 'id_driver'),
			'idMobil' => array(self::BELONGS_TO, 'MtMobil', 'id_mobil'),
			'users' => array(self::BELONGS_TO, 'Users', 'users_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_pinjam' => Yii::t('app', 'Id Pinjam'),
			'doc_ref' => Yii::t('app', 'Doc Ref'),
			'entry_time' => Yii::t('app', 'Entry Time'),
			'trans_date' => Yii::t('app', 'Trans Date'),
			'tanda_pengenal' => Yii::t('app', 'Tanda Pengenal'),
			'no_identitas' => Yii::t('app', 'No Identitas'),
			'jaminan' => Yii::t('app', 'Jaminan'),
			'jaminan_desc' => Yii::t('app', 'Jaminan Desc'),
			'id_pelanggan' => Yii::t('app', 'Id Pelanggan'),
			'id_kelompok' => Yii::t('app', 'Id Kelompok'),
			'tgl_pinjam' => Yii::t('app', 'Tgl Pinjam'),
			'season' => Yii::t('app', 'Season'),
			'sewa_bln' => Yii::t('app', 'Sewa Bln'),
			'sewa_hari' => Yii::t('app', 'Sewa Hari'),
			'sewa_jam' => Yii::t('app', 'Sewa Jam'),
			'trans_via' => Yii::t('app', 'Trans Via'),
			'no_bukti_bayar' => Yii::t('app', 'No Bukti Bayar'),
			'id_driver' => Yii::t('app', 'Id Driver'),
			'id_mobil' => Yii::t('app', 'Id Mobil'),
			'ongkos_sewa' => Yii::t('app', 'Ongkos Sewa'),
			'ongkos_driver' => Yii::t('app', 'Ongkos Driver'),
			'ongkos_bbm' => Yii::t('app', 'Ongkos Bbm'),
			'total_ongkos' => Yii::t('app', 'Total Ongkos'),
			'dp' => Yii::t('app', 'Dp'),
			'sisa_tagihan' => Yii::t('app', 'Sisa Tagihan'),
			'disc' => Yii::t('app', 'Disc'),
			'total' => Yii::t('app', 'Total'),
			'tgl_rencana_kembali' => Yii::t('app', 'Tgl Rencana Kembali'),
			'users_id' => Yii::t('app', 'Users'),
			'is_back' => Yii::t('app', 'Is Back'),
			'trf_bulan' => Yii::t('app', 'Trf Bulan'),
			'trf_hari' => Yii::t('app', 'Trf Hari'),
			'trf_jam' => Yii::t('app', 'Trf Jam'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_pinjam', $this->id_pinjam);
		$criteria->compare('doc_ref', $this->doc_ref, true);
		$criteria->compare('entry_time', $this->entry_time, true);
		$criteria->compare('trans_date', $this->trans_date, true);
		$criteria->compare('tanda_pengenal', $this->tanda_pengenal, true);
		$criteria->compare('no_identitas', $this->no_identitas, true);
		$criteria->compare('jaminan', $this->jaminan, true);
		$criteria->compare('jaminan_desc', $this->jaminan_desc, true);
		$criteria->compare('id_pelanggan', $this->id_pelanggan);
		$criteria->compare('id_kelompok', $this->id_kelompok);
		$criteria->compare('tgl_pinjam', $this->tgl_pinjam, true);
		$criteria->compare('season', $this->season);
		$criteria->compare('sewa_bln', $this->sewa_bln);
		$criteria->compare('sewa_hari', $this->sewa_hari);
		$criteria->compare('sewa_jam', $this->sewa_jam);
		$criteria->compare('trans_via', $this->trans_via, true);
		$criteria->compare('no_bukti_bayar', $this->no_bukti_bayar, true);
		$criteria->compare('id_driver', $this->id_driver);
		$criteria->compare('id_mobil', $this->id_mobil);
		$criteria->compare('ongkos_sewa', $this->ongkos_sewa);
		$criteria->compare('ongkos_driver', $this->ongkos_driver);
		$criteria->compare('ongkos_bbm', $this->ongkos_bbm);
		$criteria->compare('total_ongkos', $this->total_ongkos);
		$criteria->compare('dp', $this->dp);
		$criteria->compare('sisa_tagihan', $this->sisa_tagihan);
		$criteria->compare('disc', $this->disc);
		$criteria->compare('total', $this->total);
		$criteria->compare('tgl_rencana_kembali', $this->tgl_rencana_kembali, true);
		$criteria->compare('users_id', $this->users_id);
		$criteria->compare('is_back', $this->is_back);
		$criteria->compare('trf_bulan', $this->trf_bulan);
		$criteria->compare('trf_hari', $this->trf_hari);
		$criteria->compare('trf_jam', $this->trf_jam);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}