<?php

/**
 * This is the model base class for the table "mt_sys_types".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MtSysTypes".
 *
 * Columns in table "mt_sys_types" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $type_id
 * @property integer $type_no
 * @property string $next_reference
 *
 */
abstract class BaseMtSysTypes extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mt_sys_types';
	}

	public static function representingColumn() {
		return 'next_reference';
	}

	public function rules() {
		return array(
			array('type_id, type_no', 'numerical', 'integerOnly'=>true),
			array('next_reference', 'length', 'max'=>100),
			array('type_id, type_no, next_reference', 'default', 'setOnEmpty' => true, 'value' => null),
			array('type_id, type_no, next_reference', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'type_id' => Yii::t('app', 'Type'),
			'type_no' => Yii::t('app', 'Type No'),
			'next_reference' => Yii::t('app', 'Next Reference'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('type_no', $this->type_no);
		$criteria->compare('next_reference', $this->next_reference, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}