<?php

/**
 * This is the model base class for the table "barang".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Barang".
 *
 * Columns in table "barang" available as properties of the model,
 * followed by relations of table "barang" available as properties of the model.
 *
 * @property integer $barang_id
 * @property string $ref
 * @property string $desc
 * @property string $harga
 * @property integer $inactive
 *
 * @property NotaDtl[] $notaDtls
 */
abstract class BaseBarang extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'barang';
	}

	public static function representingColumn() {
		return 'ref';
	}

	public function rules() {
		return array(
			array('inactive', 'numerical', 'integerOnly'=>true),
			array('ref, desc, harga', 'safe'),
			array('ref, desc, harga, inactive', 'default', 'setOnEmpty' => true, 'value' => null),
			array('barang_id, ref, desc, harga, inactive', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'notaDtls' => array(self::HAS_MANY, 'NotaDtl', 'barang_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'barang_id' => Yii::t('app', 'Barang'),
			'ref' => Yii::t('app', 'Ref'),
			'desc' => Yii::t('app', 'Desc'),
			'harga' => Yii::t('app', 'Harga'),
			'inactive' => Yii::t('app', 'Inactive'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('barang_id', $this->barang_id);
		$criteria->compare('ref', $this->ref, true);
		$criteria->compare('desc', $this->desc, true);
		$criteria->compare('harga', $this->harga, true);
		$criteria->compare('inactive', $this->inactive);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}