<?php

/**
 * This is the model base class for the table "nota_dtl".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NotaDtl".
 *
 * Columns in table "nota_dtl" available as properties of the model,
 * followed by relations of table "nota_dtl" available as properties of the model.
 *
 * @property integer $nota_dtl_id
 * @property integer $nota_id
 * @property integer $barang_id
 * @property string $jml
 * @property string $harga_satuan
 * @property string $total_harga_1
 * @property string $disc_per
 * @property string $disc_rp
 * @property string $total_harga_2
 *
 * @property Barang $barang
 * @property Nota $nota
 */
abstract class BaseNotaDtl extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'nota_dtl';
	}

	public static function representingColumn() {
		return 'jml';
	}

	public function rules() {
		return array(
			array('nota_id, barang_id', 'numerical', 'integerOnly'=>true),
			array('jml, harga_satuan, total_harga_1, disc_per, disc_rp, total_harga_2', 'safe'),
			array('nota_id, barang_id, jml, harga_satuan, total_harga_1, disc_per, disc_rp, total_harga_2', 'default', 'setOnEmpty' => true, 'value' => null),
			array('nota_dtl_id, nota_id, barang_id, jml, harga_satuan, total_harga_1, disc_per, disc_rp, total_harga_2', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'barang' => array(self::BELONGS_TO, 'Barang', 'barang_id'),
			'nota' => array(self::BELONGS_TO, 'Nota', 'nota_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'nota_dtl_id' => Yii::t('app', 'Nota Dtl'),
			'nota_id' => Yii::t('app', 'Nota'),
			'barang_id' => Yii::t('app', 'Barang'),
			'jml' => Yii::t('app', 'Jml'),
			'harga_satuan' => Yii::t('app', 'Harga Satuan'),
			'total_harga_1' => Yii::t('app', 'Total Harga 1'),
			'disc_per' => Yii::t('app', 'Disc Per'),
			'disc_rp' => Yii::t('app', 'Disc Rp'),
			'total_harga_2' => Yii::t('app', 'Total Harga 2'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('nota_dtl_id', $this->nota_dtl_id);
		$criteria->compare('nota_id', $this->nota_id);
		$criteria->compare('barang_id', $this->barang_id);
		$criteria->compare('jml', $this->jml, true);
		$criteria->compare('harga_satuan', $this->harga_satuan, true);
		$criteria->compare('total_harga_1', $this->total_harga_1, true);
		$criteria->compare('disc_per', $this->disc_per, true);
		$criteria->compare('disc_rp', $this->disc_rp, true);
		$criteria->compare('total_harga_2', $this->total_harga_2, true);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}