<?php

/**
 * This is the model base class for the table "mt_mobil".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MtMobil".
 *
 * Columns in table "mt_mobil" available as properties of the model,
 * followed by relations of table "mt_mobil" available as properties of the model.
 *
 * @property integer $id_mobil
 * @property string $nopol
 * @property string $jenis
 * @property integer $tahun
 * @property string $tarif_12
 * @property string $tarif_24
 * @property string $tarif_high_12
 * @property string $tarif_high_24
 * @property string $tarif_bulanan
 * @property double $overtime
 * @property double $discount_other_rental
 *
 * @property MtKasKeluar[] $mtKasKeluars
 * @property MtKasMasuk[] $mtKasMasuks
 */
abstract class BaseMtMobil extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mt_mobil';
	}

	public static function representingColumn() {
		return 'nopol';
	}

	public function rules() {
		return array(
			array('nopol', 'required'),
			array('tahun', 'numerical', 'integerOnly'=>true),
			array('overtime, discount_other_rental', 'numerical'),
			array('nopol', 'length', 'max'=>10),
			array('jenis', 'length', 'max'=>50),
			array('tarif_12, tarif_24, tarif_high_12, tarif_high_24, tarif_bulanan', 'length', 'max'=>20),
			array('jenis, tahun, tarif_12, tarif_24, tarif_high_12, tarif_high_24, tarif_bulanan, overtime, discount_other_rental', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_mobil, nopol, jenis, tahun, tarif_12, tarif_24, tarif_high_12, tarif_high_24, tarif_bulanan, overtime, discount_other_rental', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mtKasKeluars' => array(self::HAS_MANY, 'MtKasKeluar', 'id_mobil'),
			'mtKasMasuks' => array(self::HAS_MANY, 'MtKasMasuk', 'id_mobil'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_mobil' => Yii::t('app', 'Id Mobil'),
			'nopol' => Yii::t('app', 'Nopol'),
			'jenis' => Yii::t('app', 'Jenis'),
			'tahun' => Yii::t('app', 'Tahun'),
			'tarif_12' => Yii::t('app', 'Tarif 12'),
			'tarif_24' => Yii::t('app', 'Tarif 24'),
			'tarif_high_12' => Yii::t('app', 'Tarif High 12'),
			'tarif_high_24' => Yii::t('app', 'Tarif High 24'),
			'tarif_bulanan' => Yii::t('app', 'Tarif Bulanan'),
			'overtime' => Yii::t('app', 'Overtime'),
			'discount_other_rental' => Yii::t('app', 'Discount Other Rental'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_mobil', $this->id_mobil);
		$criteria->compare('nopol', $this->nopol, true);
		$criteria->compare('jenis', $this->jenis, true);
		$criteria->compare('tahun', $this->tahun);
		$criteria->compare('tarif_12', $this->tarif_12, true);
		$criteria->compare('tarif_24', $this->tarif_24, true);
		$criteria->compare('tarif_high_12', $this->tarif_high_12, true);
		$criteria->compare('tarif_high_24', $this->tarif_high_24, true);
		$criteria->compare('tarif_bulanan', $this->tarif_bulanan, true);
		$criteria->compare('overtime', $this->overtime);
		$criteria->compare('discount_other_rental', $this->discount_other_rental);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}