<?php

/**
 * This is the model base class for the table "mt_driver".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MtDriver".
 *
 * Columns in table "mt_driver" available as properties of the model,
 * followed by relations of table "mt_driver" available as properties of the model.
 *
 * @property integer $id_driver
 * @property string $nama
 * @property string $telp
 * @property integer $inactive
 *
 * @property MtPinjamKendaraan[] $mtPinjamKendaraans
 */
abstract class BaseMtDriver extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mt_driver';
	}

	public static function representingColumn() {
		return 'nama';
	}

	public function rules() {
		return array(
			array('nama', 'required'),
			array('inactive', 'numerical', 'integerOnly'=>true),
			array('nama', 'length', 'max'=>50),
			array('telp', 'length', 'max'=>30),
			array('telp, inactive', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_driver, nama, telp, inactive', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mtPinjamKendaraans' => array(self::HAS_MANY, 'MtPinjamKendaraan', 'id_driver'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_driver' => Yii::t('app', 'Id Driver'),
			'nama' => Yii::t('app', 'Nama'),
			'telp' => Yii::t('app', 'Telp'),
			'inactive' => Yii::t('app', 'Inactive'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_driver', $this->id_driver);
		$criteria->compare('nama', $this->nama, true);
		$criteria->compare('telp', $this->telp, true);
		$criteria->compare('inactive', $this->inactive);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}