<?php

/**
 * This is the model base class for the table "mt_kelompok_pelanggan".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MtKelompokPelanggan".
 *
 * Columns in table "mt_kelompok_pelanggan" available as properties of the model,
 * followed by relations of table "mt_kelompok_pelanggan" available as properties of the model.
 *
 * @property integer $id_kelompok
 *
 * @property MtPinjamKendaraan[] $mtPinjamKendaraans
 */
abstract class BaseMtKelompokPelanggan extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mt_kelompok_pelanggan';
	}

	public static function representingColumn() {
		return 'id_kelompok';
	}

	public function rules() {
		return array(
			array('id_kelompok', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mtPinjamKendaraans' => array(self::HAS_MANY, 'MtPinjamKendaraan', 'id_kelompok'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_kelompok' => Yii::t('app', 'Id Kelompok'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_kelompok', $this->id_kelompok);

		return new CActiveDataProvider(get_class($this), array(
			'criteria' => $criteria,
		));
	}
}